services:
  # 1. PostgreSQL Database
  - type: psql
    name: dinevra-db
    plan: free
    databaseName: dinevra
    user: dinevra_admin

  # 2. Redis Cache & Pub/Sub
  - type: redis
    name: dinevra-redis
    plan: free

  # 3. Go Web Service (Backend API)
  - type: web
    name: dinevra-backend
    env: go
    plan: free
    rootDir: dinevra-backend
    buildCommand: go build -o api ./cmd/api
    startCommand: ./api
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dinevra-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: dinevra-redis
          type: redis
          property: connectionString
      - key: PORT
        value: 8080
      - key: STRIPE_SECRET_KEY
        value: sk_test_placeholder
      - key: JWT_SECRET
        value: K8lgu42mXy8CwHBwSMkl4qtVsgLtDYIaciCQvScedf+L30RzwdY1hWvbxK+3CIMAmUd1UbExWVyShXTTCBda3w==

  # 4. React Static Frontend
  - type: web
    name: dinevra-dashboard
    env: static
    plan: free
    rootDir: dinevra-dashboard
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          name: dinevra-backend
          type: web
          envVarKey: RENDER_EXTERNAL_URL
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
